myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nbapp.urls')),
    
]

handler404 = 'nbapp.views.error_404_view'

myproject/nbapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('tbp-table2-delete/<int:id>', views.tbp_table2_delete, name="tbp-table2-delete"),
    path('tbp-table2-list/', views.tbp_table2_list, name="tbp-table2-list"),
    path('tbp-table2-breakdown/<int:id>', views.tbp_table2_breakdown, name="tbp-table2-breakdown"),
    path('test/', views.test, name="test"),
    path('emiten-list/', views.emiten_list, name="emiten-list"),
    path('emiten-add/', views.emiten_add, name="emiten-add"),
    path('emiten-detail/<int:id>', views.emiten_detail, name="emiten-detail"),
    path('emiten-edit/<int:id>', views.emiten_edit, name="emiten-edit"),
    path('emiten-delete/<int:id>', views.emiten_delete, name="emiten-delete"),
    path('emiten-updated/<int:id>', views.emiten_updated, name="emiten-updated"),

]

myproject/nbapp/models.py
from django.db import models

#base model emiten
class Emiten(models.Model):
    emiten_code = models.TextField(db_column='emiten_code', blank=True, null=True)  # Field name made lowercase.
    emiten_name = models.TextField(db_column='emiten_name', blank=True, null=True)  # Field name made lowercase.
    class Meta:
        db_table = 'emiten'
        ordering = ['emiten_code']
    def __unicode__(self):
        return self.emiten_code
    def __str__(self):
        #return "%s %s" % (self.emiten_code, self.emiten_name)
        return self.emiten_code

#base model tbp_table2
class TbpTable2(models.Model):
    title = models.TextField(db_column='title', blank=True, null=True)
    source = models.TextField(db_column='source', blank=True, null=True)
    date = models.DateField(db_column='date', blank=True, null=True)
    paragraph = models.TextField(db_column='paragraph', blank=True, null=True)
    emiten = models.ForeignKey(Emiten, on_delete=models.PROTECT, blank=True, null=True)
    class Meta:
        db_table = 'tbp_table2'
    def __unicode__(self):
        return self.title

myproject/nbapp/forms.py
from django import forms  
from .models import Emiten, TbpTable2
from bootstrap_datepicker_plus import DatePickerInput

class EmitenForm(forms.ModelForm):  
    class Meta:  
        model = Emiten  
        fields = "__all__"  

class TbpTable2Form(forms.ModelForm):
    class Meta:
        model=TbpTable2
        fields = "__all__"  
        #fields = ['date']
        widgets = {
            'date': DatePickerInput(),
        }

myproject/nbapp/views.py
from django.shortcuts import render, redirect 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Emiten, TbpTable2
from .filters import EmitenFilter, TbpTable2Filter
from .forms import EmitenForm, TbpTable2Form
from .nbapputils import Nbfunctions
import pandas as pd
import string
import re
import random
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.tokenize import sent_tokenize
import os
from django.conf import settings
import pickle


def home(request):
    return render(request, "home.html",{})

def about(request):
    return render(request, "about.html",{})


def tbp_table2_list(request):
    tbp_table2_list=TbpTable2.objects.all().order_by('-date')
    emiten_list=Emiten.objects.all().order_by('emiten_name')
    return render(request, 'tbp-table2-list.html', {'tbp_table2_list':tbp_table2_list, 'emiten_list': emiten_list})


def tbp_table2_delete(request, id):
    tbp_table2 = TbpTable2.objects.get(id=id)
    try:
        tbp_table2.delete()
    except:
        print("except")
    return redirect("/tbp-table2-list/") 

def tbp_table2_breakdown(request, id):
    tbp_table2 = TbpTable2.objects.get(id=id)
    percentage=1
    df_0, df_1copy, df0, df1, TF0, TF1, IDF0, IDF1, TFIDF0, TFIDF1, percentTFIDF0, percentTFIDF1, PriorPOS,  PriorNEG, ListSent=Nbfunctions.nbprocess(tbp_table2.paragraph, percentage)
    percentagePOS, percentageNEG= getPersentase(ListSent)
    return render(request, 'tbp-table2-breakdown.html', {
        "id":id, 
        "tbp_table2":tbp_table2,
        "outputs":ListSent,
        "df_0":df_0,  
        "df_1copy": df_1copy, 
        "df0": df0,
        "df1": df1,
        "TF0": TF0,
        "TF1": TF1,
        "IDF0": IDF0,
        "IDF1": IDF1,
        "TFIDF0": TFIDF0,
        "TFIDF1": TFIDF1,
        "percentTFIDF0":percentTFIDF0,
        "percentTFIDF1": percentTFIDF1,
        "PriorPOS": PriorPOS,
        "PriorNEG": PriorNEG,
        "percentagePOS":percentagePOS,
        "percentageNEG":percentageNEG})


def emiten_add(request):
    if request.method == "POST":  
        form = EmitenForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/tbp-table2-list/')  
            except:  
                pass  
    else:  
        form = EmitenForm()  
    return render(request,'emiten-add.html',{'form':form})

def emiten_list(request):
    emiten_list = Emiten.objects.all()
    emiten_filter = EmitenFilter(request.GET, queryset=emiten_list)
    emiten_filter_qs= emiten_filter.qs
    paginator = Paginator(emiten_filter_qs, 5)  # Show 5 rows per page
    page = request.GET.get('page')
    try:
        emiten_filter_qs = paginator.page(page)
    except PageNotAnInteger:
        emiten_filter_qs = paginator.page(1)
    except EmptyPage:
        emiten_filter_qs = paginator.page(paginator.num_pages)
    return render(request, 'emiten-list.html', {'emiten_filter': emiten_filter, 'emiten_filter_qs':emiten_filter_qs})

def emiten_detail(request, id):
    emiten=Emiten.objects.get(id=id)
    return render(request, "emiten-detail.html",{"emiten":emiten})

def emiten_edit(request, id):
    emiten= Emiten.objects.get(id=id)
    return render(request, "emiten-edit.html", {'emiten':emiten})

def emiten_updated(request, id):  
    emiten = Emiten.objects.get(id=id)  
    form = EmitenForm(request.POST, instance = emiten)  
    if form.is_valid():  
        form.save()  
        return redirect("/emiten-detail/"+str(id))  
    return render(request, 'emiten-edit.html', {'emiten': emiten})  

def emiten_delete(request, id):
    emiten = Emiten.objects.get(id=id)
    try:
        emiten.delete()
    except:
        print("except")
    return redirect("/emiten-list/") 

def getPersentase(listSentence):
    percentagePOS_count=0
    percentageNEG_count=0
    percentage_count=0
    for k, v in listSentence.items():
        if (v=="POS"):
            percentagePOS_count=percentagePOS_count+1
        else:
            percentageNEG_count=percentageNEG_count+1
        percentage_count=percentage_count+1
    percentagePOS=str(round(100*percentagePOS_count/percentage_count, 2))+" %"
    percentageNEG=str(round(100*percentageNEG_count/percentage_count, 2))+" %"
    
    return percentagePOS, percentageNEG

def test(request):
    testdata=""
    option=""
    checked1="checked"
    checked2=""
    checked3=""
    checked4=""
    ListSent=""
    df_0=""  
    df_1copy=""
    df0=""
    df1=""
    TF0=""
    TF1="" 
    IDF0=""
    IDF1=""
    TFIDF0=""
    TFIDF1=""
    percentTFIDF0="" 
    percentTFIDF1=""
    percentagePOS="" 
    percentageNEG=""
    PriorPOS=""  
    PriorNEG=""
    if request.method == "POST":
        testdata=request.POST["rawdata"]
        option=request.POST["inlineRadioOptions"]
        if (option=="10"):
            checked1="checked"
        elif (option=="25"):
            checked2="checked";
        elif (option=="50"):
            checked3="checked"
        elif (option=="100"):
            checked4="checked";
        percentage=int(option)/100
        df_0, df_1copy, df0, df1, TF0, TF1, IDF0, IDF1, TFIDF0, TFIDF1, percentTFIDF0, percentTFIDF1, PriorPOS,  PriorNEG, ListSent=Nbfunctions.nbprocess(testdata, percentage)
        percentagePOS, percentageNEG= getPersentase(ListSent)
        

    return render(request, "test.html",{
        "testdata":testdata, 
        "option": option, 
        "checked1":checked1, 
        "checked2":checked2, 
        "checked3":checked3, 
        "checked4":checked4, 
        "df_0":df_0,  
        "df_1copy": df_1copy, 
        "df0": df0,
        "df1": df1,
        "TF0": TF0,
        "TF1": TF1,
        "IDF0": IDF0,
        "IDF1": IDF1,
        "TFIDF0": TFIDF0,
        "TFIDF1": TFIDF1,
        "percentTFIDF0":percentTFIDF0,
        "percentTFIDF1": percentTFIDF1,
        "PriorPOS": PriorPOS,
        "PriorNEG": PriorNEG,
        "percentagePOS": percentagePOS,
        "percentageNEG": percentageNEG,
        "outputs":ListSent,
        })

def error_404_view(request, exception):
    return render(request,'error_404.html', {})

myproject/nbapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About {% endblock %}

{% block content %}
<div class="container">
  <h1 class="jumbotron-heading">About</h1>
  <p>
Investasi mempunyai pengertian sebagai suatu keputusan (commitment) yang diambil oleh manajemen untuk mengalokasikan sumber daya perusahaan yang didasarkan atas pertimbangan yang sejalan dengan sasaran jangka panjang (kebijakan manajemen) dengan tujuan memaksimalkan nilai atau kekayaan perusahaan dimasa mendatang (Wisnubroto dan Suyanto, 2019 ).
  </p>
  <p>
Banyak cara yang digunakan untuk dapat menginvestasikan harta kita, salah satunya cara adalah dengan berinvestasi di saham. Secara sederhana saham dapat diartikan sebagai alat kepemilikan seseorang atau badan dalam suatu perusahaan yang berwujud selembar kertas yang menerangkan bahwa pemilik kertas tersebut adalah pemilik perusahaan yang menerbitkan kertas tersebut. Setiap perusahaan yang menerbitkan kertas berharga tersebut dengan tujuan mendapatkan modal atau dana tambahan disebut emiten. Harga saham setiap emiten pun mengalami pergerakan naik turun yang disebabkan berbagai faktor yang menyebabkan investor kesulitan untuk membeli saham  sesuai untuk kebutuhan investasi mereka.
  </p>
  <p>
    Terdapat beberapa penelitian sebelumnya yang menggunakan metode
    Naive Bayes sebagai classifier salah satunya yaitu penelitian Analisis Sentimen
    Terhadap Pemerintahan Joko Widodo Pada Media Sosial Twitter Menggunakan
    Algoritma Naives Bayes Classifier (Mahardhika & Zuliarso, 2018). Penulis
    menerapkan algoritma untuk mendeteksi sentimen dengan tahapan analisis data
    untuk penentuan rasio data latih dan data test. Data preprocessing meliputi case
    folding, normalisasi fitur, tokenizing dan stopword removal dengan klasifikasi
    menggunakan Naive Bayes Classifier dan menghasilkan output.
  </p>
  <center>
      <a href="{% url 'home' %}" class="btn btn-primary my-2">Back to Home</a>
  </center>
</div>

{% endblock %}

myproject/nbapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    
    <!-- datatable -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    
    <!--jquery-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
  <script>
    function moreless(dotsid, moreid, buttonid) {
      var dots = document.getElementById(dotsid);
      var moreText = document.getElementById(moreid);
      var btnText = document.getElementById(buttonid);
    
      if (dots.style.display === "none") {
        dots.style.display = "inline";
        btnText.innerHTML = "read more"; 
        moreText.style.display = "none";
      } else {
        dots.style.display = "none";
        btnText.innerHTML = "read less"; 
        moreText.style.display = "inline";
      }
    }
    </script>
  <script>
    $(document).ready(function() {
      var table = $('#tbp-table2-datatable').DataTable();
      $('#emiten-list-select').on('change', function () {
                    table.search(this.value ).draw();
      })
    } );
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
  
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">NB App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      

      

    </ul>
  </div>
</nav>
<br>
    <div class="container">
      {% block content %}
      {% endblock %}
    <br><br>
  </body>
</html>

myproject/nbapp/templates/emiten-add.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Add Emiten {% endblock %}

{% block content %}

<div class="container">

    <h2>Add Emiten</h2>
    <form method="POST" class="post-form" action="/emiten-add/">
        {% csrf_token %}
        <div class="form-group">
            <label>Emiten Code</label>
            <input class="form-control"  type="text" name="emiten_code" id="id_emiten_code" value="{{emiten.emiten_code}}">
        </div>
        <div class="form-group">
            <label>Emiten Name</label>
            <input class="form-control"  type="text" name="emiten_name" id="id_emiten_name" value="{{emiten.emiten_name}}">
        </div>
        <a href="{% url 'emiten-list' %}" class="btn btn-primary my-2">Cancel</a>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
    

</div>


{% endblock %}

myproject/nbapp/templates/emiten-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Emiten Detail {% endblock %}

{% block content %}

<div class="container">
    
    <h2>Emiten Detail</h2>
    <p>Emiten Code: {{emiten.emiten_code}}</p>
    <p>Emiten Name: {{emiten.emiten_name}}</p>
   
    <a href="{% url 'emiten-list' %}" class="btn btn-primary my-2">Back to Emiten List</a>
</div>


{% endblock %}

myproject/nbapp/templates/emiten-edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Emiten Edit {% endblock %}

{% block content %}

<div class="container">

    <h2>Emiten Update</h2>
    <form method="POST" class="post-form" action="/emiten-updated/{{emiten.id}}">
        {% csrf_token %}
        <div class="form-group">
            <label>Emiten Code</label>
            <input class="form-control"  type="text" name="emiten_code" id="id_emiten_code" value="{{emiten.emiten_code}}">
        </div>
        <div class="form-group">
            <label>Emiten Name</label>
            <input class="form-control"  type="text" name="emiten_name" id="id_emiten_name" value="{{emiten.emiten_name}}">
        </div>
        <a href="{% url 'emiten-list' %}" class="btn btn-primary my-2">Cancel</a>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
    

</div>


{% endblock %}

myproject/nbapp/templates/emiten-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Emiten {% endblock %}

{% block content %}


<div>
    <a href="{% url 'tbp-table2-list' %}" class="btn btn-primary my-2">Back to News Data List</a>
    
    <h2 align="center">Emiten List</h2>
</div>
<div>
    <form method="get">
        {{ emiten_filter.form.as_p }}
        <button class="btn btn-primary my-2" type="submit">Search</button>
    </form>
    
</div>
<div class="pagination">
    <span class="step-links">

        {% if emiten_filter_qs.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ emiten_filter_qs.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ emiten_filter_qs.number }} of {{ emiten_filter_qs.paginator.num_pages }} pages
        </span>

        {% if emiten_filter_qs.has_next %}
        <a href="?page={{ emiten_filter_qs.next_page_number }}">next</a>
        <a href="?page={{ emiten_filter_qs.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    
</div>
<div>
    
    <table class="table" id="emitenTable">
        <thead>
            <tr>
                <th scope="col">Emiten Code</th>
                <th scope="col">Emiten Name</th>
                <th scope="col" colspan="2">Action</th>
            </tr>
        </thead>
        {% for emiten in emiten_filter_qs %}
        <tbody>
            <tr>
                <td><a href="{% url 'emiten-detail' id=emiten.id %}">{{emiten.emiten_code}}</a></td>
                <td>{{emiten.emiten_name}}</td>
                <td><a href="{% url 'emiten-edit' id=emiten.id %}" class="btn btn-primary my-2">Update</a></td>
                <td><a href="{% url 'emiten-delete' id=emiten.id %}" class="btn btn-primary my-2">Delete</a></td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <a href="{% url 'emiten-add' %}" class="btn btn-primary my-2">Add New Emiten</a>
</div>
{% endblock %}

myproject/nbapp/templates/emiten-updated.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Emiten Detail Updated {% endblock %}

{% block content %}

<div class="container">
    <h2>Emiten Updated</h2>
    <p>Emiten Name: {{emiten.emiten_code}}</p>
    <p>Emiten Code: {{emiten.emiten_name}}</p>
    <a href="{% url 'emiten-list' %}" class="btn btn-primary my-2">Back to Emiten List</a>
</div>


{% endblock %}

myproject/nbapp/templates/emitten-edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %} emiten Edit {% endblock %}

{% block content %}

<div class="container">

    <h2>emiten Update</h2>
    <form method="POST" class="post-form" action="/nbapp/emiten-updated/{{emiten.id}}">
        {% csrf_token %}
        <div class="form-group">
            <label>emiten Code</label>
            <input class="form-control"  type="text" name="emiten_code" id="id_emiten_code" value="{{emiten.emiten_code}}">
        </div>
        <div class="form-group">
            <label>emiten Name</label>
            <input class="form-control"  type="text" name="emiten_name" id="id_emiten_name" value="{{emiten.emiten_name}}">
        </div>
        <a href="{% url 'emiten-list' %}" class="btn btn-primary my-2">Cancel</a>
        <button type="submit" class="btn btn-success">Update</button>
    </form>
    

</div>


{% endblock %}

myproject/nbapp/templates/emitten-list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} emiten {% endblock %}

{% block content %}


<div>
    <a href="{% url 'tbp-table2-list' %}" class="btn btn-primary my-2">Back to News Data List</a>
    
    <h2 align="center">Emiten List</h2>
</div>
<div>
    <form method="get">
        {{ emiten_filter.form.as_p }}
        <button class="btn btn-primary my-2" type="submit">Search</button>
    </form>
    
</div>
<div class="pagination">
    <span class="step-links">

        {% if emiten_filter_qs.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ emiten_filter_qs.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ emiten_filter_qs.number }} of {{ emiten_filter_qs.paginator.num_pages }} pages
        </span>

        {% if emiten_filter_qs.has_next %}
        <a href="?page={{ emiten_filter_qs.next_page_number }}">next</a>
        <a href="?page={{ emiten_filter_qs.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    
</div>
<div>
    
    <table class="table" id="emitenTable">
        <thead>
            <tr>
                <th scope="col">Emiten Code</th>
                <th scope="col">Emiten Name</th>
                <th scope="col" colspan="2">Action</th>
            </tr>
        </thead>
        {% for emiten in emiten_filter_qs %}
        <tbody>
            <tr>
                <td><a href="{% url 'emiten-detail' id=emiten.id %}">{{emiten.emiten_code}}</a></td>
                <td>{{emiten.emiten_name}}</td>
                <td><a href="{% url 'emiten-edit' id=emiten.id %}" class="btn btn-primary my-2">Update</a></td>
                <td><a href="{% url 'emiten-delete' id=emiten.id %}" class="btn btn-primary my-2">Delete</a></td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <a href="{% url 'emiten-add' %}" class="btn btn-primary my-2">Add New emiten</a>
</div>
{% endblock %}

myproject/nbapp/templates/error_404.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Page not found</title>

  </head>

</nav>
<br>
    <div class="container">
    	<br>Page not found<br>
      <center>
        <img src="{% static 'images/404-error.jpg' %}" class="img-fluid" alt="Broken gif">
      </center>
      <div class="center">
      	<a class="btn btn-primary" href="{% url 'home' %}" role="button">Back to Home</a>
      </div>
    </div>
    <br><br>
    <center><small>Copyright &copy; 127.0.0.1:8000 - All Reserved</small></center>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

myproject/nbapp/templates/tbp-table2-breakdown.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Breakdown {% endblock %}

{% block content %}
<div class="container">
  <a href="{% url 'tbp-table2-list' %}" class="btn btn-primary my-2">Back to News Data</a>
  <h4>{{tbp_table2.title}}</h4>
  <p>{{tbp_table2.paragraph|slice:":400"}}<span id="dots{{tbp_table2.id}}">...</span><span id="more{{tbp_table2.id}}" style="display: none;">{{tbp_table2.paragraph|slice:"400:"}}</span><button onclick="moreless('dots{{tbp_table2.id}}', 'more{{tbp_table2.id}}', 'buttonid{{tbp_table2.id}}')" id="buttonid{{tbp_table2.id}}">read more</button></p>



  <p>Persentase Positive: {{percentagePOS}}</p>
  <p>Persentase Negative: {{percentageNEG}}</p>

  <h4>Breakdown</h4>

  <table class="table" id="tb_sentences">
    <thead>
        <tr>
            <th scope="col">Sentence</th>
            <th scope="col">Label</th>
        </tr>
    </thead>
    {% for key,value in outputs.items %}
    <tbody>
        <tr>
            <td>{{key}}</td>
            <td>{{value}}</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
  
</div>

{% endblock %}